Bump `setup-just` actions to v4 (#138)
## What has changed
We hit this (flaky) deprecation warning in one of the CI test:
```
Node 20 is being deprecated. This workflow is running with Node 24 by default. If you need to temporarily use Node 20, you can set the ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true environment variable. For more information see: https://github.blog/changelog/2025-09-[1](https://github.com/umigv/maverick/actions/runs/29880321172/job/88799531640?pr=124#step:4:1)9-deprecation-of-node-20-on-github-actions-runners/
Run extractions/setup-just@v2
(node:2497) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: no release for just matching version specifier
```

This bumps the `setup-just` action from v2 to v4 so that it uses Node
24.

## Testing plan
CI passes (again)